name: Test API

on:
  push:
    branches:
      - master
      - api-sentiment
  pull_request:
    branches:
      - master
      - api-sentiment
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest --maxfail=5 --disable-warnings
